---
- block:
  - name: Delete Launch Configuration
    environment:
      AWS_DEFAULT_REGION: "{{ Sts.Region }}"
      AWS_ACCESS_KEY_ID: "{{ Sts.Credentials.get('AWS_ACCESS_KEY_ID') }}"
      AWS_ACCESS_KEY: "{{ Sts.Credentials.get('AWS_ACCESS_KEY') }}"
      AWS_SECRET_ACCESS_KEY: "{{ Sts.Credentials.get('AWS_SECRET_ACCESS_KEY') }}"
    shell: aws autoscaling delete-launch-configuration --launch-configuration-name "{{ lc_name }}"
    register: command_result
    ignore_errors: True
  
  - name: Launch Configuration register result
    debug: msg="{{ command_result }}"

  - name: Fail if Launch Configuration Delete did not succeed
    fail:
      msg: "FAILED TO DELETE LAUNCH CONFIG {{ command_result.stderr }}"
    when: command_result.rc != 0
  tags:
    - delete
