---
- block:
  - name: create timestamp fact
    set_fact:
      current_timestamp: "{{ (ansible_date_time.date + ansible_date_time.time) | regex_replace('[^\\d]','') }}"

  - name: Launch Config gather facts
    set_fact:  
      lc_name: "{{ launchConfig.get('Name') | default(omit)}}"
      lc_delete: "{{ launchConfig.get('Delete') | default(False) | bool }}"
      lc_image_id: "{{ launchConfig.get('image-id') | default(omit) }}"
      lc_access_key: "{{ launchConfig.get('key-name') | default(omit) }}"
      lc_security_groups: "{{ launchConfig.get('security-groups') | default(omit) }}"
      lc_instance_type: "{{ launchConfig.get('instance-type') | default('t2.micro') }}"
      lc_volume_name: "{{ launchConfig.get('volume-device_name') | default(omit) }}"
      lc_volume_type: "{{ launchConfig.get('volume-type') | default(omit) }}"
      lc_delete_on_termination: "{{ launchConfig.get('volumes-delete_on_termination') | default(False) | bool }}"
      debug: "{{ debug | default(False) | bool }}"            
  tags:
    - always