# # Assume Role
# - name: Assume Role
#   hosts: "{{ env }}"
#   gather_facts: no
#   roles:
#     - aws-sts

# Modify ASG launch Config
- name: Stack Deployment
  hosts: "{{ env }}"
  #environment: "{{ Sts.Credentials }}"
  roles:
    - aws-asg-launchConfig

# You can add post deployment plays here as required