# Integer values are declared separately & c'not be part of map 

LaunchConfig_size: 120
LaunchConfig_volume: 1000

# Admin Role for STS service
Sts:
  Role: arn:aws:iam::713475812120:role/AdminAccessforDeploy
  Region: us-east-1

launchConfig:
  Name: shankar
  Delete: True
  image-id: ami-43221439
  key-name: docker
  security-groups: ['sg-03b6aa75', 'sg-3c6e5b4e' ]
  instance-type: t2.micro
  volume-device_name: /dev/sda1
  volume-type: io1
  volumes-delete_on_termination: True
